### ISSUE TITLE
CAN NOT install Toolkit2 1.4 on Ubuntu-20.4 with Python 3.8

### ISSUE THREAD

**Issue by PJ5168** [rockchip-linux/rknn-toolkit2#108]
There is no Python 3.6 available, therefore use 3.8.
The numpy, bfloat16 are installed.
ERROR message as following:

(RKNN38) pj@B560M:~/rknn-toolkit2$ pip install bfloat16
Requirement already satisfied: bfloat16 in /home/pj/anaconda3/envs/RKNN38/lib/python3.8/site-packages (1.1)

(RKNN38) pj@B560M:~/rknn-toolkit2$ sudo pip3 install packages/rknn_toolkit2*cp38*.whl
Processing ./packages/rknn_toolkit2-1.4.0_22dcfef4-cp38-cp38-linux_x86_64.whl
Collecting bfloat16==1.1
  Using cached bfloat16-1.1.tar.gz (550 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tz_fjqmv/bfloat16/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tz_fjqmv/bfloat16/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-tz_fjqmv/bfloat16/pip-egg-info
         cwd: /tmp/pip-install-tz_fjqmv/bfloat16/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tz_fjqmv/bfloat16/setup.py", line 10, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by sarranetor** [comment]
I am having the same error and using ubuntu 20.4 and python 3,8 as well ..

**Comment by ttxida** [comment]
i fixed this by installing to venv python3-dev

**Comment by PJ5168** [comment]
OK with 1.5
Thanks!~

**Comment by PJ5168** [comment]
WHL build ok with Python3.8
but still fail to load the rknn.api module
------------------------------------------------------------
Python 3.8.0 (default, Nov  6 2019, 21:49:08)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rknn.api import RKNN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rknn'
>>>

**Comment by chuqingq** [comment]
> from rknn.api import RKNN

I have the same problem.
