### ISSUE TITLE
RK3568 rknn-toolkit-lite2推理Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by LiBai531** [rockchip-linux/rknn-toolkit2#14]
模型转换环境：rknn-toolkit2 1.2.0-f7bb160f
推理环境：rknn-toolkit-lite2 1.2.0

在模拟器中可以正常推理，在开发板上推理报错：Segmentation fault (core dumped)

**Comment by HunterRockchips** [comment]
有更多信息吗？

**Comment by LiBai531** [comment]
> 

推理报错没有更多的信息，init runtime成功后推理时直接Segmentation fault：
D RKNN: [02:20:24.071] Total Weight Memory  : 10767872
D RKNN: [02:20:24.071] Total Internal Memory: 15777792
D RKNN: [02:20:24.071] Total Memory: 26545664
D RKNN: [02:20:24.072] Total Allocate Memory: 31314216
--> Init runtime environment done
--> inference
D RKNN: [02:20:24.151] argb mode info: chw: [3, 384, 384], stride: 384, tile chw: [3, 384, 74], startxyz: [0, 0, 0]
D RKNN: [02:20:24.152] argb mode info: chw: [3, 384, 384], stride: 384, tile chw: [3, 384, 74], startxyz: [0, 74, 0]
D RKNN: [02:20:24.152] argb mode info: chw: [3, 384, 384], stride: 384, tile chw: [3, 384, 74], startxyz: [0, 148, 0]
D RKNN: [02:20:24.152] argb mode info: chw: [3, 384, 384], stride: 384, tile chw: [3, 384, 74], startxyz: [0, 222, 0]
D RKNN: [02:20:24.152] argb mode info: chw: [3, 384, 384], stride: 384, tile chw: [3, 384, 74], startxyz: [0, 296, 0]
D RKNN: [02:20:24.152] argb mode info: chw: [3, 384, 384], stride: 384, tile chw: [3, 384, 14], startxyz: [0, 370, 0]
D RKNN: [02:20:24.152] normalize target: NPU
D RKNN: [02:20:24.154] Get NPU frequency: 600MHz
Segmentation fault (core dumped)

使用的模型：https://drive.google.com/file/d/1QoZieqroca5cPoChgLbv41_ovaqFCPho/view?usp=sharing

**Comment by HunterRockchips** [comment]
这样暂时看不出问题原因，建议更新最新版本，看是否已经修复该问题

**Comment by LiBai531** [comment]
> 这样暂时看不出问题原因，建议更新最新版本，看是否已经修复该问题

暂时没有看到有更新的版本；此外，尝试更换模型，同样的，模型转换环境：rknn-toolkit2 1.2.0-f7bb160f，推理环境：rknn-toolkit-lite2 1.2.0，在模拟器中可以正常推理，在开发板上推理报错：E RKNN: [06:15:37.184] ERROR: unsuport Equal op in cunrrent

**Comment by LiBai531** [comment]
> 
rknn-toolkit2支持的操作与实际推理时支持的操作可能存在不对齐的情况是吗

**Comment by HunterRockchips** [comment]
对实际板端推理阶段还不支持，但是toolkit2阶段支持

**Comment by LiBai531** [comment]
好的，谢谢
