### ISSUE TITLE
rknn在pc和rk3568上推理结果不同

### ISSUE THREAD

**Issue by FengMu1995** [rockchip-linux/rknn-toolkit2#15]
模型有三个输出,用3568真机实测,只有一个输出和在pc上跑出来的结果差距很大,输出全为1,模型并没有进行量化后处理之类的操作
我看了这三个输出对应的不同算子,只有RKNN: [19:25:28.295] 150 exSoftmax13    input0.4是出错的输出才有的算子.

**Comment by jayshonzs** [comment]
遇到相同问题，两个输出，PC上模拟是对的，实机上调用RKNPU只有一个输出是对的，第二个输出是错的。

**Comment by jayshonzs** [comment]
请问题主，你的问题解决了吗，是什么原因造成的。感谢

**Comment by jayshonzs** [comment]
我的第二个输出错误，是softmax操作
