### ISSUE TITLE
yolov5 6.0

### ISSUE THREAD

**Issue by Ha-Dj** [rockchip-linux/rknn-toolkit2#155]
yolov5 6.0 推理结果中出现负数？

**Comment by alexw914** [comment]
老哥解决了吗，我在v6.2里训练转换为RKNN，预测结果有很多框而且有一些负数。

**Comment by alexw914** [comment]
找到了问题，瑞芯微提供的仓库onnx导出自带sigmoid算子，他官方代码示例没有修改，导致sigmoid算了两次。

**Comment by Ha-Dj** [comment]
> 找到了问题，瑞芯微提供的仓库onnx导出自带sigmoid算子，他官方代码示例没有修改，导致sigmoid算了两次。

感谢感谢，忘记再查看issue了，我后面也解决了。
