### ISSUE TITLE
ITX 3588J

### ISSUE THREAD

**Issue by RavinduTharanga** [rockchip-linux/rknn-toolkit2#165]
I use ITX 3588J device.I tried to install rknn-toolkit2 to the device.when I try to install requirements.txt  it's not install tensorflow 2.6. currently I installed tensorflow 2.10. this is the error message 
```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.6.2 (from versions: 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.13.0rc0)
ERROR: No matching distribution found for tensorflow==2.6.2
```

and also I couldn't run this file rknn_toolkit2-1.4.0_22dcfef4-cp36-cp36m-linux_x86_64.whl
it says 
`ERROR: rknn_toolkit2-1.4.0_22dcfef4-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.
`
Please solve this

**Comment by thnak** [comment]
to install rknn-toolkit please install [the packages for aarch64](https://github.com/rockchip-linux/rknn-toolkit2/tree/master/rknn_toolkit_lite2/packages)
maybe you have to rebuild tensorflow
