### ISSUE TITLE
docker 在哪里下载

### ISSUE THREAD

**Issue by mabuyun** [rockchip-linux/rknn-toolkit2#18]
百度云下载链接点击失败了，repo 里也没有 docker 文件夹
从哪里能下载 docker

**Comment by ganleiboy** [comment]
> 百度云下载链接点击失败了，repo 里也没有 docker 文件夹 从哪里能下载 docker

在提供的百度云下载链接里面有docker目录。
![image](https://user-images.githubusercontent.com/35066897/182084731-5996131e-8b5c-461b-9ec0-d1fbb6c0936d.png)
