### ISSUE TITLE
Unsupport Loop(不支持onnx的loop算子)

### ISSUE THREAD

**Issue by sqsu-pg** [rockchip-linux/rknn-toolkit2#181]
请问一下有在之后的版本里支持loop算子的计划吗?

**Comment by yuyun2000** [comment]
不好整啊，他们才刚刚完成了不怎么好使的动态shape，你还想搞动态迭代？

**Comment by sqsu-pg** [comment]
在rknntoolkit2版本更新到1.6.0之后，这个问题解决了，瑞芯微部分支持了动态权重卷积。我测试的npu驱动版本是0.8.8，低于这个版本的驱动未做测试。
