### ISSUE TITLE
Convertion error from yolov8 to RKNN

### ISSUE THREAD

**Issue by laitathei** [rockchip-linux/rknn-toolkit2#184]
Platform:
torch: 1.13.1+cu116
onnx: 1.10.0
onnxruntime: 1.10.0
rknn-toolkit2 version: 1.5.0+1fa95b5c

I am trying to convert yolov8-seg.pt to rknn format
The first step, i follow yolov8 official tutorial to convert it to onnx format. Here is the code
```
from ultralytics import YOLO
model = YOLO('yolov8n-seg.pt')
success = model.export(format='onnx',opset=12)
```

The second step, i try to convert onnx file to rknn format. Here is the code
```
from rknn.api import RKNN



if __name__ == "__main__":
    ONNX_MODEL = "./yolov8n-seg.onnx"
    RKNN_MODEL = "./yolov8n-seg.rknn"
    platform = "rk3588"
    width = 640
    height = 640

    # Create RKNN object
    rknn = RKNN()

    # pre-process config
    print("--> config model")
    #rknn.config(mean_values=[[0,0,0]], std_values=[[127.5, 127.5, 127.5]], target_platform=platform)
    rknn.config(mean_values=[[0,0,0]], std_values=[[255, 255, 255]], target_platform=platform)
    # Load model
    print("--> load model")
    ret = rknn.load_onnx(ONNX_MODEL)
    if ret != 0:
        print("load model failed!")
        exit(ret)
    print("Done")

    # Build model
    print("--> build model")
    ret = rknn.build(do_quantization=True, dataset="dataset.txt")
    if ret != 0:
        print("build model failed!")
        exit(ret)
    print("Done")

    # Export rknn model
    print("--> export rknn model")
    ret = rknn.export_rknn(RKNN_MODEL)
    if ret != 0:
        print("export model failed!")
        exit(ret)
    print("Done")

    rknn.release()
```
However, it pop up something warning for me.
```
W __init__: rknn-toolkit2 version: 1.5.0+1fa95b5c
--> config model
done
--> Loading model
Loading : 100%|████████████████████████████████████████████████| 175/175 [00:00<00:00, 50184.82it/s]
done
--> Building model
W build: found outlier value, this may affect quantization accuracy
const name                        abs_mean    abs_std     outlier value
model.22.cv3.1.1.conv.weight      0.12        0.18        -12.310     
Analysing : 100%|███████████████████████████████████████████████| 209/209 [00:00<00:00, 5965.44it/s]
Quantizating : 100%|█████████████████████████████████████████████| 209/209 [00:01<00:00, 174.88it/s]
W build: The default input dtype of 'images' is changed from 'float32' to 'int8' in rknn model for performance!
                       Please take care of this change when deploy rknn model with Runtime API!
W build: The default output dtype of 'output0' is changed from 'float32' to 'int8' in rknn model for performance!
                      Please take care of this change when deploy rknn model with Runtime API!
W build: The default output dtype of 'output1' is changed from 'float32' to 'int8' in rknn model for performance!
                      Please take care of this change when deploy rknn model with Runtime API!
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
done
--> Export RKNN model
done
```

After that it still provide the rknn file for me, but it cause some error during inference
I am using below code to inference rknn
```
import numpy as np
import cv2
import time
from rknnlite.api import RKNNLite

IMG_SIZE = 640

if _name_ == '_main_':
    rknn_model = 'yolov8n-seg.rknn'
    rknn_lite = RKNNLite()
    ret = rknn_lite.load_rknn(rknn_model)
    ret = rknn_lite.init_runtime(core_mask=RKNNLite.NPU_CORE_AUTO)
    img = cv2.imread("./bus.jpg")
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, dsize=(IMG_SIZE,IMG_SIZE))
    outputs = rknn_lite.inference(inputs=[img])
    print(outputs)
```

However, the result is wrong
```
I RKNN: [17:07:17.914] RKNN Runtime Information: librknnrt version: 1.5.0 (e6fe0c678@2023-05-25T08:09:20)
I RKNN: [17:07:17.915] RKNN Driver Information: version: 0.8.2
I RKNN: [17:07:17.915] RKNN Model Information: version: 4, toolkit version: 1.5.0+1fa95b5c(compiler version: 1.5.0 (e6fe0c678@2023-05-25T16:15:03)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
E RKNN: [17:07:24.530] failed to submit!, op id: 139, op name: Mul:/model.22/Mul_2, flags: 0x5, task start: 382, task number: 11, run task counter: 5, int status: 0, please try updating to the latest version of the toolkit2 and runtime from: https://eyun.baidu.com/s/3eTDMk6Y (PWD: rknn)
W RKNN: [17:07:24.531] Output(output0): size_with_stride larger than model origin size, if need run OutputOperator in NPU, please call rknn_create_memory using size_with_stride.
[array([[[[318.77222],
         [318.77222],
         [318.77222],
         ...,
         [318.77222],
         [318.77222],
         [318.77222]],

        [[318.77222],
         [318.77222],
         [318.77222],
         ...,
         [318.77222],
         [318.77222],
         [318.77222]],

        [[318.77222],
         [318.77222],
         [318.77222],
         ...,
         [318.77222],
         [318.77222],
         [318.77222]],

        ...,

        [[318.77222],
         [318.77222],
         [318.77222],
         ...,
         [318.77222],
         [318.77222],
         [318.77222]],

        [[318.77222],
         [318.77222],
         [318.77222],
         ...,
         [318.77222],
         [318.77222],
         [318.77222]],

        [[318.77222],
         [318.77222],
         [318.77222],
         ...,
         [318.77222],
         [318.77222],
         [318.77222]]]], dtype=float32), array([[[[ 1.3423584e-01,  2.4609905e-01,  1.5660849e-01, ...,
           3.8033491e-01,  2.9084435e-01,  4.6982548e-01],
         [ 6.9355190e-01,  5.1457077e-01,  4.2508021e-01, ...,
           9.3965095e-01,  7.3829722e-01,  7.6066983e-01],
         [ 6.0406137e-01,  4.0270755e-01,  3.5796228e-01, ...,
           1.0291415e+00,  6.9355190e-01,  7.8304249e-01],
         ...,
         [ 2.4609905e-01, -6.7117937e-02, -1.3423586e-01, ...,
           1.7898113e-01,  1.5660849e-01,  8.9490563e-02],
         [ 2.4609905e-01,  6.7117922e-02, -4.4745293e-02, ...,
           1.7898113e-01,  1.7898113e-01,  1.5660849e-01],
         [ 2.6847172e-01,  1.1186320e-01,  2.2372635e-02, ...,
           2.2372635e-02,  2.2372635e-02,  4.4745278e-02]],

        [[-1.1186322e-01, -2.2372644e-01, -2.0135379e-01, ...,
          -1.7898116e-01, -2.0135379e-01, -1.7898116e-01],
         [-1.3423586e-01, -2.4609907e-01, -2.4609907e-01, ...,
          -2.4609907e-01, -2.4609907e-01, -2.4609907e-01],
         [-1.5660851e-01, -2.4609907e-01, -2.4609907e-01, ...,
          -2.4609907e-01, -2.4609907e-01, -2.4609907e-01],
         ...,
         [-6.7117937e-02, -2.2372644e-01, -2.0135379e-01, ...,
          -2.2372644e-01, -2.0135379e-01, -2.4609907e-01],
         [-4.4745293e-02, -1.5660851e-01, -1.7898116e-01, ...,
          -2.0135379e-01, -1.7898116e-01, -2.0135379e-01],
         [-7.4505806e-09, -1.5660851e-01, -1.7898116e-01, ...,
          -1.7898116e-01, -1.5660851e-01, -1.5660851e-01]],

        [[-2.4609907e-01, -2.6847172e-01, -2.6847172e-01, ...,
          -2.6847172e-01, -2.6847172e-01, -2.6847172e-01],
         [-2.6847172e-01, -2.6847172e-01, -2.6847172e-01, ...,
          -2.6847172e-01, -2.6847172e-01, -2.6847172e-01],
         [-2.6847172e-01, -2.6847172e-01, -2.6847172e-01, ...,
          -2.6847172e-01, -2.6847172e-01, -2.6847172e-01],
         ...,
         [-2.4609907e-01, -2.6847172e-01, -2.6847172e-01, ...,
          -2.6847172e-01, -2.6847172e-01, -2.6847172e-01],
         [-2.2372644e-01, -2.6847172e-01, -2.6847172e-01, ...,
          -2.6847172e-01, -2.6847172e-01, -2.6847172e-01],
         [-2.4609907e-01, -2.6847172e-01, -2.6847172e-01, ...,
          -2.6847172e-01, -2.6847172e-01, -2.6847172e-01]],

        ...,

        [[ 5.3694344e-01,  1.1857500e+00,  1.2752407e+00, ...,
           1.7003208e+00,  1.5213397e+00,  1.2081227e+00],
         [ 6.7117929e-01,  1.4318491e+00,  1.5884576e+00, ...,
           1.9464198e+00,  1.7226934e+00,  1.3647312e+00],
         [ 7.3829722e-01,  1.3423586e+00,  1.5213397e+00, ...,
           2.1030283e+00,  1.8121841e+00,  1.5437124e+00],
         ...,
         [ 2.2372642e-01,  4.2508021e-01,  4.9219814e-01, ...,
           4.4745284e-01,  4.9219814e-01,  6.7117929e-01],
         [ 3.1321698e-01,  6.4880663e-01,  7.3829722e-01, ...,
           5.1457077e-01,  6.0406137e-01,  6.4880663e-01],
         [ 3.1321698e-01,  7.3829722e-01,  8.7253302e-01, ...,
           6.0406137e-01,  7.1592456e-01,  7.1592456e-01]],

        [[-1.5660851e-01,  6.7117922e-02,  1.1186320e-01, ...,
           1.7898113e-01,  1.3423584e-01,  3.1321698e-01],
         [ 1.7898113e-01,  7.8304249e-01,  8.0541515e-01, ...,
           8.2778776e-01,  6.2643397e-01,  6.4880663e-01],
         [ 8.9490563e-02,  6.2643397e-01,  7.8304249e-01, ...,
           8.2778776e-01,  5.3694344e-01,  6.0406137e-01],
         ...,
         [ 2.9084435e-01,  5.3694344e-01,  6.0406137e-01, ...,
           6.7117922e-02,  2.0135377e-01,  2.2372642e-01],
         [ 4.6982548e-01,  8.0541515e-01,  6.4880663e-01, ...,
          -7.4505806e-09,  8.9490563e-02,  1.5660849e-01],
         [ 4.9219814e-01,  7.1592456e-01,  6.7117929e-01, ...,
           1.3423584e-01,  2.0135377e-01,  2.2372642e-01]],

        [[-8.9490578e-02,  2.0135377e-01,  1.1186320e-01, ...,
           1.0291415e+00,  8.9490569e-01,  1.1186321e+00],
         [-2.2372644e-01,  3.5796228e-01,  2.0135377e-01, ...,
           2.0806558e+00,  1.7898114e+00,  1.7450662e+00],
         [-2.2372644e-01,  4.4745284e-01,  2.4609905e-01, ...,
           2.3043821e+00,  2.1030283e+00,  2.0359104e+00],
         ...,
         [-1.7898116e-01,  1.1186320e-01,  1.3423584e-01, ...,
           4.0270755e-01,  5.1457077e-01,  8.7253302e-01],
         [-1.5660851e-01,  4.2508021e-01,  2.9084435e-01, ...,
           2.2372642e-01,  3.3558962e-01,  8.0541515e-01],
         [ 2.2372635e-02,  6.2643397e-01,  5.3694344e-01, ...,
           3.3558962e-01,  4.2508021e-01,  7.3829722e-01]]]],
      dtype=float32)]
```

Can anyone give some guidelines how to convert yolov8n-seg.pt to rknn format and inference it in rk3588 platform?

**Comment by Kracozebr** [comment]
Any updates? face the same error with other model
```
 REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 
```

**Comment by Galaxy-Ding** [comment]
same problems for me

**Comment by qmcreeper** [comment]
Maybe you can change Detect() such us:
1. replace `.chunk` with `.split` in dist2bbox()
2. `* self.strides` cause a warning "op(Mul:Mul_***) has undefined broadcast type..." when qnt,so change 'Mul' broadcast type or 'self.strides' dim refer to https://github.com/rockchip-linux/rknn-toolkit2/blob/master/doc/RKNN_Compiler_Support_Operator_List_v1.5.0.pdf

**Comment by laitathei** [comment]
I try the first step, but it still not working to me
for the second step, I don't know how to implement. Would you like to explain clearly in chinese. Thank you

**Comment by Galaxy-Ding** [comment]
> r the second step, I don't know how to implement. Would you like to explain clearly in chinese. Thank you

thanks, i will tried it

**Comment by laitathei** [comment]
may be you can contact me via wechat
my wechat id is wxid_y4ihk4jup2cs22, user id is hei

**Comment by laitathei** [comment]
[issue.zip](https://github.com/rockchip-linux/rknn-toolkit2/files/12246587/issue.zip)

**Comment by laitathei** [comment]
[issue.zip](https://github.com/rockchip-linux/rknn-toolkit2/files/12246622/issue.zip)

**Comment by qmcreeper** [comment]
加个simplify=true，这样silu()导出的时候不会添加mul，替换激活函数的方案大概率因为这个，还是mul的broadcast不对，那个文档有详细的mul格式要求和示例

**Comment by Galaxy-Ding** [comment]
那么请问有试过 rknn toolkit，欲转换到 rk3399pro

**Comment by laitathei** [comment]
@qmcreeper
I tried to add simplify=true in ```rknn.export_rknn(RKNN_MODEL,simplify=True)``` but it still produce error on mul broadcast error. After using netron to visualize onnx network structure, I found that the problem may come from the size problem. The size of mul layer that casue the error is (1,8400). How can we change it to fit rknn operator requirement?

**Comment by qmcreeper** [comment]
> @qmcreeper I tried to add simplify=true in `rknn.export_rknn(RKNN_MODEL,simplify=True)` but it still produce error on mul broadcast error. After using netron to visualize onnx network structure, I found that the problem may come from the size problem. The size of mul layer that casue the error is (1,8400). How can we change it to fit rknn operator requirement?

`self.strides` size is  (1,8400)，its format is [b,n]. yo need to change the dist2bbox() output to [b,c,h,w], and repeat `self.strides` to [h, w] or [b,c,h,w].

**Comment by Galaxy-Ding** [comment]
> > @qmcreeper I tried to add simplify=true in `rknn.export_rknn(RKNN_MODEL,simplify=True)` but it still produce error on mul broadcast error. After using netron to visualize onnx network structure, I found that the problem may come from the size problem. The size of mul layer that casue the error is (1,8400). How can we change it to fit rknn operator requirement?
> 
> `self.strides` size is (1,8400)，its format is [b,n]. yo need to change the dist2bbox() output to [b,c,h,w], and repeat `self.strides` to [h, w] or [b,c,h,w].

我想问下 dfl 这部分卷积，在rknntoolkit2 是可以转换的额？？我看了下 rknntoolkit1 的时候 会报错，当然，你上述的改动我已经做了

![image](https://github.com/rockchip-linux/rknn-toolkit2/assets/54030287/42606f21-7f72-410a-a60c-2d523fd16129)

**Comment by qmcreeper** [comment]
> > > @qmcreeper I tried to add simplify=true in `rknn.export_rknn(RKNN_MODEL,simplify=True)` but it still produce error on mul broadcast error. After using netron to visualize onnx network structure, I found that the problem may come from the size problem. The size of mul layer that casue the error is (1,8400). How can we change it to fit rknn operator requirement?
> > 
> > 
> > `self.strides` size is (1,8400)，its format is [b,n]. yo need to change the dist2bbox() output to [b,c,h,w], and repeat `self.strides` to [h, w] or [b,c,h,w].
> 
> 我想问下 dfl 这部分卷积，在rknntoolkit2 是可以转换的额？？我看了下 rknntoolkit1 的时候 会报错，当然，你上述的改动我已经做了
> 
> ![image](https://user-images.githubusercontent.com/54030287/258017039-42606f21-7f72-410a-a60c-2d523fd16129.png)

建议能改四维的全改四维，我这边1和2都能过

**Comment by Galaxy-Ding** [comment]
可以分享下你的onnx 吗？我目前就是 全改4维也没过

**Comment by laitathei** [comment]
@qmcreeper 
我是新手, 不知道該如何把(1, 8400)改成４維改成(b,c,h,w)又可以符合最後輸出大小(1, 116, 8400)
你能把Detect的部分分享一下嗎，感謝大佬

**Comment by laitathei** [comment]
i think i solve this problem
```
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
```

but it still cannot have any segmentation result. Will this parameter affect the mode?
```
W build: found outlier value, this may affect quantization accuracy
const name                        abs_mean    abs_std     outlier value
model.22.cv3.1.1.conv.weight      0.12        0.18        -12.310   
```

**Comment by qmcreeper** [comment]
> i think i solve this problem
> 
> ```
> E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
> E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
> E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
> E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
> E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
> ```
> 
> but it still cannot have any segmentation result. Will this parameter affect the model result?
> 
> ```
> W build: found outlier value, this may affect quantization accuracy
> const name                        abs_mean    abs_std     outlier value
> model.22.cv3.1.1.conv.weight      0.12        0.18        -12.310   
> ```

Mixed-Precision Quantization， fp16 instead of int8

**Comment by Galaxy-Ding** [comment]
> > > > @qmcreeper I tried to add simplify=true in `rknn.export_rknn(RKNN_MODEL,simplify=True)` but it still produce error on mul broadcast error. After using netron to visualize onnx network structure, I found that the problem may come from the size problem. The size of mul layer that casue the error is (1,8400). How can we change it to fit rknn operator requirement?
> > > 
> > > 
> > > `self.strides` size is (1,8400)，its format is [b,n]. yo need to change the dist2bbox() output to [b,c,h,w], and repeat `self.strides` to [h, w] or [b,c,h,w].
> > 
> > 
> > 我想问下 dfl 这部分卷积，在rknntoolkit2 是可以转换的额？？我看了下 rknntoolkit1 的时候 会报错，当然，你上述的改动我已经做了
> > ![image](https://user-images.githubusercontent.com/54030287/258017039-42606f21-7f72-410a-a60c-2d523fd16129.png)
> 
> 建议能改四维的全改四维，我这边1和2都能过

结果我这边出来了，应该是包含了 y8 dfl 
![image](https://github.com/rockchip-linux/rknn-toolkit2/assets/54030287/a60086ae-39b1-42c4-b3a3-292310a73301)
![image](https://github.com/rockchip-linux/rknn-toolkit2/assets/54030287/aa760626-b4c7-4676-9a2a-8b8f677a4765)
![image](https://github.com/rockchip-linux/rknn-toolkit2/assets/54030287/74a1387e-17a5-452b-91aa-fa3dbad92336)

主要是改了这几个地方，但是输出的结果 并没有人和 indces

![image](https://github.com/rockchip-linux/rknn-toolkit2/assets/54030287/a20714e7-2cec-41c5-bd8a-44378be0af04)

**Comment by laitathei** [comment]
I think I solved this issue.
The process of Using Yolov8 official guide to convert its onnx file will not cause any problem.
The main problem come from onnx to rknn. You have to follow hybrid quantization method to get the rknn,
The hybrid quantization method inside https://github.com/rockchip-linux/rknn-toolkit2/blob/master/doc/Rockchip_User_Guide_RKNN_Toolkit2_CN-1.5.0.pdf this doc.

**Comment by Jeremiah0425** [comment]
> i think i solve this problem
> 
> ```
> E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
> E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
> E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
> E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
> E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
> ```
> 
> but it still cannot have any segmentation result. Will this parameter affect the model result?
> 
> ```
> W build: found outlier value, this may affect quantization accuracy
> const name                        abs_mean    abs_std     outlier value
> model.22.cv3.1.1.conv.weight      0.12        0.18        -12.310   
> ```

hello，How did you solve this problem?

**Comment by Jeremiah0425** [comment]
> I think I solved this issue. The process of Using Yolov8 official guide to convert its onnx file will not cause any problem. The main problem come from onnx to rknn. You have to follow hybrid quantization method to get the rknn, The hybrid quantization method inside https://github.com/rockchip-linux/rknn-toolkit2/blob/master/doc/Rockchip_User_Guide_RKNN_Toolkit2_CN-1.5.0.pdf this doc.

i have followed hybrid quantization method to get the rknn， but problem not solved

**Comment by letessarini** [comment]
Anyone managed to solve this problem: --> Running model for camera inference
I RKNN: [13:52:25.482] RKNN Runtime Information: librknnrt version: 1.5.2 (c6b7b351a@2023-08-23T15:28:22)
I RKNN: [13:52:25.482] RKNN Driver Information: version: 0.8.2
W RKNN: [13:52:25.482] Current driver version: 0.8.2, recommend to upgrade the driver to the new version: >= 0.8.8
I RKNN: [13:52:25.484] RKNN Model Information: version: 6, toolkit version: 1.5.2+b642f30c(compiler version: 1.5.2 (c6b7b351a@2023-08-23T07:39:01)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
W RKNN: [13:52:25.707] Output(output0): size_with_stride larger than model origin size, if need run OutputOperator in NPU, please call rknn_create_memory using size_with_stride.

**Comment by jipperspippers** [comment]
I have quite a different solution to this. For specifically YOLOV8S I removed a node at the end and received a 3 output solution instead. 

```python
import torch
from ultralytics import YOLO
from ultralytics.nn.modules import Detect

model = YOLO("best.pt")

# let the NPU run the Box (cv2) and Class (cv3) convolutions.
# just skip the "View/Reshape/Transpose" that crashes the RK3588.
def split_forward(self, x):
    res = []
    for i in range(self.nl):
        bboxes = self.cv2[i](x[i])
        classes = self.cv3[i](x[i])
        res.append(torch.cat((bboxes, classes), 1))
    return res

# Apply this split
Detect.forward = split_forward

print("Exporting optimized 3-output ONNX...")
model.export(format="onnx", opset=12, simplify=True)
```

Note the output will be 3 grids with variable sizes for large, medium and small detection purposes.
