### ISSUE TITLE
toolkit2能否添加3.9的包。

### ISSUE THREAD

**Issue by rainote2020** [rockchip-linux/rknn-toolkit2#196]
目前发现很多3588板的支持系统都是debian11，而debian11原生python环境是3.9，能否提供3.9下的toolkit包。

**Comment by 0312birdzhang** [comment]
有啊， https://github.com/rockchip-linux/rknn-toolkit2/tree/master/rknn_toolkit_lite2/packages

**Comment by DDX1126** [comment]
那你配置Python3.8或者python3.10不就好了，配置不难，没必要让别人适应你

**Comment by rainote2020** [comment]
> 那你配置Python3.8或者python3.10不就好了，配置不难，没必要让别人适应你

抱歉，不赞同您说的，大部分情况下受业务程序制约是不能更换python版本。
后续发现，debian下可以跑lite来推理，另寻一个Ubuntu环境进行转模型即可，此issue关闭。

**Comment by DDX1126** [comment]
哦哦哦，那你业务量大，让rk给你适配吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月15日(周五) 下午5:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rockchip-linux/rknn-toolkit2] toolkit2能否添加3.9的包。 (Issue #196)




  
那你配置Python3.8或者python3.10不就好了，配置不难，没必要让别人适应你
  
抱歉，不赞同您说的，大部分情况下受业务程序制约是不能更换python版本。
 后续发现，debian下可以跑lite来推理，另寻一个Ubuntu环境进行转模型即可，此issue关闭。
