### ISSUE TITLE
init_runtime with target='rk3568' failed

### ISSUE THREAD

**Issue by jules-ai** [rockchip-linux/rknn-toolkit2#2]
I got my rk3568 board connected in docker that you offered:

`root@my-docker:/workspace/rknn-toolkit2/examples/tflite/mobilenet_v1# adb devices`
`List of devices attached`
`90f931708d91ca10        device`
`root@my-docker:/workspace/rknn-toolkit2/examples/tflite/mobilenet_v1# lsusb`
`Bus 002 Device 003: ID 2207:0006`

But when I try to run a py script, the init_runtime with target='rk3568' returns a failed code(-9) ERROR_PIPE.
`--> Init runtime environment`
`I NPUTransfer: Starting NPU Transfer Client, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:36)`
`E RKNNAPI: rknn_init,  server connect fail!  ret = -9(ERROR_PIPE)!`
`E init_runtime: Catch exception when init runtime!`
`E init_runtime: Traceback (most recent call last):`
`E init_runtime:   File "rknn/api/rknn_base.py", line 2553, in rknn.api.rknn_base.RKNNBase.init_runtime`
`E init_runtime:   File "rknn/api/rknn_runtime.py", line 367, in rknn.api.rknn_runtime.RKNNRuntime.build_graph`
`E init_runtime: Exception: RKNN init failed. error code: RKNN_ERR_DEVICE_UNAVAILABLE`
`Init runtime environment failed`

The script code is rknn-toolkit2/examples/tflite/mobilenet_v1/test.py, I added only **target='rk3568'** in param of init_runtime.

I suppose there might be some problems with this function?

**Comment by dddyyyplus** [comment]
Did you solve this problem？

**Comment by jules-ai** [comment]
It is a bug in rknn_server of ancient version. Fixed since v1.1.1.
