### ISSUE TITLE
onnx转rknn时BN层消失了

### ISSUE THREAD

**Issue by brallnb** [rockchip-linux/rknn-toolkit2#208]
在netron中看onnx转rknn后BN层消失了，是默认和conv层融合了吗？
还有就是pth->onnx->rknn模型转换和板端推理都没有报错和warning，但是推理结果就是不对，求大佬指点还能从哪儿查起？

**Comment by Calsia** [comment]
hi我也遇到了类似问题，你有解决吗

**Comment by Calsia** [comment]
https://github.com/rockchip-linux/rknn-toolkit2/issues/333   我的描述放到了这里
