### ISSUE TITLE
模型build阶段Segmentation fault (core dumped)错误

### ISSUE THREAD

**Issue by yuyun2000** [rockchip-linux/rknn-toolkit2#227]
打开config的debug接口，几个过程全部没有报错

I fuse_ops done.
I fuse_ops check ...
I fuse_ops check results:
I     "encoder_out": cosine = 0.9999998807907104,  euclidean = 0.0009352223132736981
I     "new_cached_len_0": cosine = 1.0,  euclidean = 0.0
I     "new_cached_len_1": cosine = 1.0,  euclidean = 0.0
I     "new_cached_len_2": cosine = 1.0,  euclidean = 0.0
I     "new_cached_len_3": cosine = 1.0,  euclidean = 0.0
I     "new_cached_len_4": cosine = 1.0,  euclidean = 0.0
I     "new_cached_avg_0": cosine = 0.9999998807907104,  euclidean = 1.6473821062845673e-07
I     "new_cached_avg_1": cosine = 0.9999998807907104,  euclidean = 1.43532489005338e-07
I     "new_cached_avg_2": cosine = 0.9999998807907104,  euclidean = 1.648256784392288e-07
I     "new_cached_avg_3": cosine = 0.9999998807907104,  euclidean = 6.869095869888042e-08
I     "new_cached_avg_4": cosine = 0.9999998807907104,  euclidean = 3.3592169756957446e-07
I     "new_cached_key_0": cosine = 1.0,  euclidean = 2.209559897892177e-05
I     "new_cached_key_1": cosine = 1.0,  euclidean = 2.4434482838842086e-05
I     "new_cached_key_2": cosine = 1.0,  euclidean = 1.4904534509696532e-05
I     "new_cached_key_3": cosine = 0.9999998807907104,  euclidean = 5.501795840245904e-06
I     "new_cached_key_4": cosine = 1.0,  euclidean = 2.4626551748951897e-05
I     "new_cached_val_0": cosine = 1.0,  euclidean = 1.6581705494900234e-05
I     "new_cached_val_1": cosine = 1.0,  euclidean = 1.7510981706436723e-05
I     "new_cached_val_2": cosine = 1.0,  euclidean = 9.549356946081389e-06
I     "new_cached_val_3": cosine = 0.9999998807907104,  euclidean = 3.939724138035672e-06
I     "new_cached_val_4": cosine = 1.0,  euclidean = 1.735315890982747e-05
I     "new_cached_val2_0": cosine = 1.0,  euclidean = 5.271678674034774e-05
I     "new_cached_val2_1": cosine = 1.0,  euclidean = 4.4921318476554006e-05
I     "new_cached_val2_2": cosine = 1.0,  euclidean = 2.2312284272629768e-05
I     "new_cached_val2_3": cosine = 1.0,  euclidean = 9.27707787923282e-06
I     "new_cached_val2_4": cosine = 1.0,  euclidean = 4.185505167697556e-05
I     "new_cached_conv1_0": cosine = 1.0,  euclidean = 4.654557051253505e-05
I     "new_cached_conv1_1": cosine = 0.9999998807907104,  euclidean = 5.992973092361353e-05
I     "new_cached_conv1_2": cosine = 1.0,  euclidean = 2.851524914149195e-05
I     "new_cached_conv1_3": cosine = 1.0,  euclidean = 1.644925941945985e-05
I     "new_cached_conv1_4": cosine = 1.0,  euclidean = 4.6051485696807504e-05
I     "new_cached_conv2_0": cosine = 1.0,  euclidean = 5.4996027756715193e-05
I     "new_cached_conv2_1": cosine = 1.0,  euclidean = 6.258243229240179e-05
I     "new_cached_conv2_2": cosine = 1.0,  euclidean = 2.896862497436814e-05
I     "new_cached_conv2_3": cosine = 1.0,  euclidean = 1.776733188307844e-05
I     "new_cached_conv2_4": cosine = 0.9999998807907104,  euclidean = 0.00010627044684952125
I 
I sparse_weight ...
I sparse_weight done.
I 
I recover_const_share ...
I recover_const_share done.
I 
I rknn building ...
之后命令行里就报错了，等我再跑一下贴出fault前的信息

**Comment by yuyun2000** [comment]
I rknn building ...
I RKNN: [10:26:32.286] compress = 0, conv_eltwise_activation_fuse = 1, global_fuse = 1, multi-core-model-mode = 7, output_optimize = 1,enable_argb_group=0
I RKNN: librknnc version: 1.5.2 (c6b7b351a@2023-08-23T07:30:34)
D RKNN: [10:26:32.686] RKNN is invoked
D RKNN: [10:26:34.184] >>>>>> start: N4rknn19RKNNSetOpTargetPassE
D RKNN: [10:26:34.184] <<<<<<<< end: N4rknn19RKNNSetOpTargetPassE
D RKNN: [10:26:34.184] >>>>>> start: N4rknn16RKNNAddFirstConvE
D RKNN: [10:26:34.186] <<<<<<<< end: N4rknn16RKNNAddFirstConvE
D RKNN: [10:26:34.186] >>>>>> start: N4rknn27RKNNEliminateQATDataConvertE
D RKNN: [10:26:34.209] <<<<<<<< end: N4rknn27RKNNEliminateQATDataConvertE
D RKNN: [10:26:34.209] >>>>>> start: N4rknn17RKNNTileGroupConvE
D RKNN: [10:26:34.210] <<<<<<<< end: N4rknn17RKNNTileGroupConvE
D RKNN: [10:26:34.210] >>>>>> start: N4rknn19RKNNTileFcBatchFuseE
D RKNN: [10:26:34.212] <<<<<<<< end: N4rknn19RKNNTileFcBatchFuseE
D RKNN: [10:26:34.212] >>>>>> start: N4rknn15RKNNAddConvBiasE
D RKNN: [10:26:34.213] <<<<<<<< end: N4rknn15RKNNAddConvBiasE
D RKNN: [10:26:34.213] >>>>>> start: N4rknn15RKNNTileChannelE
D RKNN: [10:26:34.215] <<<<<<<< end: N4rknn15RKNNTileChannelE
D RKNN: [10:26:34.215] >>>>>> start: N4rknn18RKNNPerChannelPrepE
D RKNN: [10:26:34.217] <<<<<<<< end: N4rknn18RKNNPerChannelPrepE
D RKNN: [10:26:34.217] >>>>>> start: N4rknn11RKNNBnQuantE
D RKNN: [10:26:34.219] <<<<<<<< end: N4rknn11RKNNBnQuantE
D RKNN: [10:26:34.219] >>>>>> start: N4rknn21RKNNFuseOptimizerPassE
D RKNN: [10:26:34.247] <<<<<<<< end: N4rknn21RKNNFuseOptimizerPassE
D RKNN: [10:26:34.247] >>>>>> start: N4rknn15RKNNTurnAutoPadE
D RKNN: [10:26:34.249] <<<<<<<< end: N4rknn15RKNNTurnAutoPadE
D RKNN: [10:26:34.249] >>>>>> start: N4rknn16RKNNInitRNNConstE
D RKNN: [10:26:34.251] <<<<<<<< end: N4rknn16RKNNInitRNNConstE
D RKNN: [10:26:34.251] >>>>>> start: N4rknn17RKNNInitCastConstE
D RKNN: [10:26:34.253] <<<<<<<< end: N4rknn17RKNNInitCastConstE
D RKNN: [10:26:34.253] >>>>>> start: N4rknn20RKNNMultiSurfacePassE
D RKNN: [10:26:34.257] <<<<<<<< end: N4rknn20RKNNMultiSurfacePassE
D RKNN: [10:26:34.257] >>>>>> start: OpEmit
D RKNN: [10:26:34.274] <<<<<<<< end: OpEmit
D RKNN: [10:26:34.274] >>>>>> start: N4rknn19RKNNLayoutMatchPassE
D RKNN: [10:26:34.279] <<<<<<<< end: N4rknn19RKNNLayoutMatchPassE
D RKNN: [10:26:34.279] >>>>>> start: N4rknn20RKNNAddSecondaryNodeE
D RKNN: [10:26:34.305] <<<<<<<< end: N4rknn20RKNNAddSecondaryNodeE
D RKNN: [10:26:34.305] >>>>>> start: OpEmit
Segmentation fault (core dumped)

**Comment by yuyun2000** [comment]
是某层的操作有问题，已经逐层排查到，也没人回复就这样吧...

**Comment by danny-zhu** [comment]
> 是某层的操作有问题，已经逐层排查到，也没人回复就这样吧...

可以把自己遇到的问题原因和解决方案分享出来，供其他人参考

**Comment by yuyun2000** [comment]
我已经说了啊~ 是网络中某层的操作有问题，我这里的是有切片操作越界了
