### ISSUE TITLE
Error on installing requirements for system (tensorflow==2.8.0)

### ISSUE THREAD

**Issue by IskanderSh2** [rockchip-linux/rknn-toolkit2#232]
When I tried to run installation on requirements.txt file, I've got an error, that a tensorflow v2.8.0 right now doesn't exists on Ubuntu's pip.
How I can solve this problem?
I already tried to change the pip source to 'https://mirror.baidu.com/pypi/simple', but it doesn't work.
(Sorry for my bad english)

**Comment by Kanken6174** [comment]
Tensorflow is not for arm, only x86-64, the rknn-toolkit2 is meant to be run on a regular pc

**Comment by IskanderSh2** [comment]
Yes, you're right :)
Just little misunderstand from me
