### ISSUE TITLE
rknn量化bert模型报错Status Message: indices element out of data bounds, idx=-120 must be within the inclusive range [-2,1]

### ISSUE THREAD

**Issue by Nidhoggof** [rockchip-linux/rknn-toolkit2#235]
<img width="1138" alt="b048dac8111f2127825dc7aacfae749" src="https://github.com/rockchip-linux/rknn-toolkit2/assets/122583195/d81679b3-a1a5-4335-bee4-d0e71cd9ae29">

**Comment by GDHNES** [comment]
朋友，你成功把bert跑起来了吗？

**Comment by GDHNES** [comment]
朋友，你成功把bert跑起来了吗？
