### ISSUE TITLE
whisper可以转rknn吗，有demo吗

### ISSUE THREAD

**Issue by xiuxiuxiu6** [rockchip-linux/rknn-toolkit2#250]
想用3588跑whisper

**Comment by wyd520520** [comment]
https://github.com/usefulsensors/useful-transformers/tree/main

**Comment by xiuxiuxiu6** [comment]
> https://github.com/usefulsensors/useful-transformers/tree/main
谢谢，这个有转换好的rknn模型的调用实例吗

**Comment by xiuxiuxiu6** [comment]
> > https://github.com/usefulsensors/useful-transformers/tree/main
> > 谢谢，这个有转换好的rknn模型的调用实例吗

是transcribe_wav.py这个吗

**Comment by AntyRia** [comment]
作者成功了吗，想问问思路或简单的demo，是把whisper编解码分开转还是一起也可以
