### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by ZlodeiBaal** [rockchip-linux/rknn-toolkit2#260]
Hi!
I am trying to run this new version of RKNN.lite. At the moment, I am trying to call for `ret = rknn_lite.init_runtime(core_mask=RKNNLite.NPU_CORE_0)`  I get this error:

> OSError: /usr/lib/librknnrt.so: invalid ELF header

I used this lib to put it into "/usr/lib/" - "https://github.com/rockchip-linux/rknn-toolkit2/tree/master/rknpu2/runtime/Linux/librknn_api/aarch64/librknnrt.so"
Did you change the installation process somehow?

I am using - friendlyelec, nanopc-t6rockchip, rk3588

It seems I am not the only one with this problem - https://gist.github.com/ZlodeiBaal/847569b24bb338566680ab2a8f22c6b2?permalink_comment_id=4791442#gistcomment-4791442

The quick hack is to use old lib - https://github.com/rockchip-linux/rknpu2/raw/master/runtime/RK3588/Linux/librknn_api/aarch64/librknnrt.so

But I hope you will fix the current version

Duplicate of "https://github.com/airockchip/rknn-toolkit2/issues/1" issue. 

Don't know which repo is core from now:)

**Comment by MustafaYounes1** [comment]
Seems that u downloaded the binary file `librknnrt.so` in an invalid format.

You can check the format of the downloaded file with `file file.format`.

[Expected output]
```
$ file librknnrt.so
librknnrt.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=7795f7cdc39c0c9f016ac0e22093bc96efd632f6, stripped
```

Try to do the following:

```
# Download RKNPU2 Runtime
git clone https://github.com/rockchip-linux/rknpu2

# Move it to /usr/lib
sudo mv rknpu2/runtime/RK3588/Linux/librknn_api/aarch64/librknnrt.so /usr/lib

# Create the librknn_api.so symbolic link
cd /usr/lib
sudo ln -s librknnrt.so librknn_api.so

# Test your installation
cd rknn-toolkit2/rknn_toolkit_lite2/examples/inference_with_lite/
python3 test.py
```

**Comment by ZlodeiBaal** [comment]
Hi, @MustafaYounes1 !
Thank you for your answer. But the repo you show "https://github.com/rockchip-linux/rknpu2" is outdated:
> This project is no longer maintained and has been moved to https://github.com/airockchip/rknn-toolkit2/tree/master/rknpu2

It has 1.5.2 version. And yes, it works as I stated in the issue:

> The quick hack is to use old lib - https://github.com/rockchip-linux/rknpu2/raw/master/runtime/RK3588/Linux/librknn_api/aarch64/librknnrt.so

The actual version is 1.6.0:
> "https://github.com/airockchip/rknn-toolkit2/tree/master/rknpu2/runtime/Linux/librknn_api/aarch64/librknnrt.so"
> "https://github.com/rockchip-linux/rknn-toolkit2/tree/master/rknpu2/runtime/Linux/librknn_api/aarch64/librknnrt.so"
And none of these libraries works.

**Comment by ZlodeiBaal** [comment]
Hmm. 
I re-downloaded this one and put the symbolic link `sudo ln -s librknnrt.so librknn_api.so` and it started working
https://github.com/airockchip/rknn-toolkit2/raw/master/rknpu2/runtime/Linux/librknn_api/aarch64/librknnrt.so

I am a bit confused, but it works now for me.

**Comment by MustafaYounes1** [comment]
Hi @ZlodeiBaal 

I did the upgrade, but got the following warning:

```
I RKNN: [14:14:13.065] RKNN Driver Information, version: 0.8.2
W RKNN: [14:14:13.065] Current driver version: 0.8.2, recommend to upgrade the driver to the new version: >= 0.8.8
```

Any idea about how to update the RKNN Driver?

**Comment by ZlodeiBaal** [comment]
I don't know. I have "I RKNN: [12:10:33.595] RKNN Driver Information, version: 0.8.8"
It probably depends on the system image from the vendor. What board do you use / what system is installed?

**Comment by MustafaYounes1** [comment]
I also think it's a matter of system image.

HW: Raxda's Rock5b
System: Ubuntu 22.04

Is it the same on your end? If yes, what system image do you have, and where I can get it  from?

Thanks in advance

**Comment by ZlodeiBaal** [comment]
No, I have this one board now - https://www.friendlyelec.com/index.php?route=product/product&product_id=292
I was experimenting with pre-installed Ubuntu 22.04 (think it's from here - https://wiki.friendlyelec.com/wiki/index.php/NanoPC-T6 )

I was testing a few networks with Rock3A, and there were a lot of problems with drivers. Only old system images from 2022 work (here is [the video](https://youtu.be/pN8mKZ5wpdQ) with the exact version). All new images have problems. But I am not sure that it's relatable for Rock 5.

**Comment by MustafaYounes1** [comment]
You're totally right..

I have seen similar issues on different boards.

The currently installed Raxda image seems to be well equipped with the required drivers (don't know its version though), the only issue with it is the RKNN driver that seems a bit outdated for the latest librknnrt.

I will try to test their [latest image](https://github.com/radxa-build/rock-5b/releases/tag/b39) (released in September 2023) 

Anyways, thanks for the info
Happy new year
Regards
