### ISSUE TITLE
ONNX转RKNN模型时出现了非法指令内核已转储（Illegal instruction - core dumped）

### ISSUE THREAD

**Issue by JSTks24** [rockchip-linux/rknn-toolkit2#291]
本人在Fedora Workstation 39上按照安装手册完整的部署了toolkit2，然后在`rknn_model_zoo-main`对应exampleYOLO项目提供的convert.py对已有的onnx模型进行了转换，却发现在转化模型的一步时运行一会后会卡住，然后提示非法指令（内核已转储），即Illegal instruction - core dumped。不知道大家有没有遇到这个问题的，现在不清楚怎么解决比较好了
![3446639a542b881c8aa0ddb26c457a3](https://github.com/rockchip-linux/rknn-toolkit2/assets/62133008/9c887d84-0b04-42c1-aa07-847bbe51779c)

**Comment by JSTks24** [comment]
补充一下，如下图
![1709992178044](https://github.com/rockchip-linux/rknn-toolkit2/assets/62133008/401837c6-2274-47aa-8aaf-78a5739f197b)

**Comment by JSTks24** [comment]
已自己完美解决

**Comment by gscholer** [comment]
> 已自己完美解决

你好, 这个问题是怎么解决的呢？我也遇到了

**Comment by jieblue** [comment]
> 已自己完美解决

请问是怎么解决的？

**Comment by dong200** [comment]
您好，怎么解决的

**Comment by jieblue** [comment]
@dong200 你是在虚拟机运行的吗？查看你的虚拟机是否开启AVX2指令集
