### ISSUE TITLE
Not a supported wheel on this platform.

### ISSUE THREAD

**Issue by AkylaiB** [rockchip-linux/rknn-toolkit2#305]
Hello,
I have an issue with rknn_toolkit2 installation  on virtual environment with python 3.8, on ubuntu os, with aarch64 architecture.
Additionally i could not install required versions of tensorflow(2.8.0) and protobuf(3.20.3), is it can be the reason of the issue?

**Comment by zen-xingle** [comment]
aarch64 is mismatched with x86_64.
