### ISSUE TITLE
onnx转rknn中出现 Reshape OP is not supported

### ISSUE THREAD

**Issue by yuanxiaohe** [rockchip-linux/rknn-toolkit2#314]
使用rknn-toolkit2的时候，将onnx模型转换成rknn的时候报  Pow OP is not supported和Reshape OP is not supported的错误：

**Comment by yuanxiaohe** [comment]
W __init__: rknn-toolkit2 version: 1.5.2+b642f30c
--> Config model
done
--> Loading model
Loading : 100%|███████████████████████████████████████████████| 482/482 [00:00<00:00, 202489.44it/s]
done
--> Building model
W build: Resize [Resize_420] convert to Deconvolution for inference speedup, but may cause result driftting.
To disable this optimization, please set 'optimization_level = 2' in 'rknn.config'
W build: Resize [Resize_442] convert to Deconvolution for inference speedup, but may cause result driftting.
To disable this optimization, please set 'optimization_level = 2' in 'rknn.config'
Analysing : 100%|███████████████████████████████████████████████| 276/276 [00:00<00:00, 6026.39it/s]
Quantizating : 100%|██████████████████████████████████████████████| 276/276 [00:05<00:00, 53.47it/s]
W build: The default input dtype of 'input' is changed from 'float32' to 'int8' in rknn model for performance!
                       Please take care of this change when deploy rknn model with Runtime API!
W build: The default output dtype of 'output' is changed from 'float32' to 'int8' in rknn model for performance!
                      Please take care of this change when deploy rknn model with Runtime API!
E RKNN: [01:09:32.416] Pow OP is not supported, continuing will result in an error, OP id: 154, OP name: Pow:Pow_559
E RKNN: [01:09:32.416] Reshape OP is not supported, continuing will result in an error, OP id: 165, OP name: Reshape:Concat_836_swap_concat_reshape_i0_out
E RKNN: [01:09:32.416] Pow OP is not supported, continuing will result in an error, OP id: 177, OP name: Pow:Pow_671
E RKNN: [01:09:32.416] Reshape OP is not supported, continuing will result in an error, OP id: 188, OP name: Reshape:Concat_836_swap_concat_reshape_i1_out
E RKNN: [01:09:32.416] Pow OP is not supported, continuing will result in an error, OP id: 200, OP name: Pow:Pow_783
E RKNN: [01:09:32.416] Reshape OP is not supported, continuing will result in an error, OP id: 211, OP name: Reshape:Concat_836_swap_concat_reshape_i2_out
E RKNN: [01:09:32.417] Reshape OP is not supported, continuing will result in an error, OP id: 213, OP name: Reshape:Concat_836_0_unsqueeze1
done
--> Export rknn model

**Comment by bai-0829** [comment]
我也遇到了同样的问题，请问解决了吗
