### ISSUE TITLE
所在现在tensorflow2.0和用它转换出的tflite构建rknn是都不行吗

### ISSUE THREAD

**Issue by shivabohemian** [rockchip-linux/rknn-toolkit2#36]

**Comment by shivabohemian** [comment]
我这边直接报错，说默认要用tensorflow 1.x

**Comment by ankh1999** [comment]
请问您找到解决方案了吗，是否可以通过config或者其他方式支持tensorflow2？又或者当前版本确实不支持tensorflow2？

**Comment by QLW-07** [comment]
tensorflow2 .tflite模型，转rknn，提示：Error loading model into tflite interpreter: index 0 is out of bounds for axis 0 with size 0；是tensorflow版本的问题吗？

**Comment by smileR-T** [comment]
> tensorflow2 .tflite模型，转rknn，提示：Error loading model into tflite interpreter: index 0 is out of bounds for axis 0 with size 0；是tensorflow版本的问 @QLW-07    请问这个问题解决了吗
