### ISSUE TITLE
RK3588 在Ubuntu下无法部署

### ISSUE THREAD

**Issue by ouyang11111** [rockchip-linux/rknn-toolkit2#40]
官方开发套件Ubuntu系统只支持x86架构，我们的RK3588是arm架构的，而arm架构开发套件（lite版本）又只支持Debian。请问如何才能部署到该板子上，只能用docker么？还是必须要重新烧录为Debian？

**Comment by HunterRockchips** [comment]
官方的开发套件是连板调试用的，就是你的PC（Ubuntu）连RK3588板子，toolkit2的量化、图优化、仿真等在PC上跑，调用推理是在RK3588的NPU上跑。

**Comment by ouyang11111** [comment]
> 



> 官方的开发套件是连板调试用的，就是你的PC（Ubuntu）连RK3588板子，toolkit2的量化、图优化、仿真等在PC上跑，调用推理是在RK3588的NPU上跑。

我知道了，我们把板子拿来ssh调试的，我已经走完流程了 ，自己虚拟机x86Ubuntu转的rknn，ssh到板子上直接跑  。

**Comment by HunterRockchips** [comment]
ok，那解决了就close这个issue吧
