### ISSUE TITLE
RK3568提示驱动有问题

### ISSUE THREAD

**Issue by Zheng-Bicheng** [rockchip-linux/rknn-toolkit2#49]
下载RKNN Toolkit Lite2后，按照手册安装。然后我下载了rknpu2，更新最新的驱动到/usr/lib。但是运行RKNN Toolkit Lite2自带的demo后提示错误如下:
`
toybrick@debian10:~/Downloads/rknn_toolkit_lite2/examples/inference_with_lite$ python3 test.py 
--> Load RKNN model
done
--> Init runtime environment
E RKNN: [04:05:28.147] failed to open rknpu module, need to insmod rknpu dirver!
E RKNN: [04:05:28.147] failed to open rknn device!
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/home/toybrick/.local/lib/python3.7/site-packages/rknnlite/api/rknn_lite.py", line 148, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 838, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

Init runtime environment failed
`
想问一下错误的原因是什么。使用的固件为toybrick最新的debian10固件，板子为toybrick的3568X

**Comment by Zheng-Bicheng** [comment]
问题已经解决，解决方案放在csdn（http://t.csdn.cn/agHx2）了，需要用sudo命令来调用NPU才能驱动的起来。

**Comment by LinoSun** [comment]
404了 所以要怎么解决。 请问 sudo运行哪个命令呢

**Comment by gujiuren** [comment]
> 404了 所以要怎么解决。 请问 sudo运行哪个命令呢

同问，怎么从根本上解决问题？

**Comment by Zheng-Bicheng** [comment]
> > 404了 所以要怎么解决。 请问 sudo运行哪个命令呢
> 
> 同问，怎么从根本上解决问题？

让系统工程师将底层设备树映射的设备文件权限修改为用户权限就可以用了。
