### ISSUE TITLE
 Invalid RKNN format. rknn_query, load_model failed #7 

### ISSUE THREAD

**Issue by AIGirl10** [rockchip-linux/rknn-toolkit2#6]
We tried to inference **ssd_mobilenet _v1** model with **C++ inference** on **Rk3566** board. But got this error
```sh
Loading model ...
rknn_init ...
I RKNN: set log level to 0
E RKNN: Invalid RKNN format
E RKNN: rknn_query, load_model failed
rknn_init fail! ret=-1
```
Tried to search the error code it said its Model Execution error, but not able to understand why its not working, because same model worked with python inference on ubuntu 16.04.

**Comment by rkchrome** [comment]
This may happened when you convert rknn version and run inferemce librknnrt.so version which does not match!

**Comment by mabuyun** [comment]
same error
```
E RKNN: [05:06:22.571] parseRKNN from buffer: Invalid RKNN format!
E RKNN: [05:06:22.571] rknn_init, load model failed!
```

**Comment by AIGirl10** [comment]
@rkchrome 

yes actually that was the issue. Works perfectly now, thanks !
