### ISSUE TITLE
Failed to submit!  op id: 227, op name: OutputOperator:139_convolutional, flags: 0x1...

### ISSUE THREAD

**Issue by frootonator** [rockchip-linux/rknn-toolkit2#87]
Hello,

I'm trying to inference YOLOv4 .rknn converted from .onnx with the help of rknn-toolkit2. It performs well on PC using test.py code from toolkit examples but fails on AIO-3568J using rknpu .cc code. It returns error during inference (rknn.run):

E RKNN: [02:49:39.674] failed to submit!, op id: 227, op name: OutputOperator:139_convolutional, flags: 0x1, task start: 0, task number: 2583, run task counter: 2322, int status: 0

Tried to convert original darknet model to .rknn but received the same mistake. Have anyone tried to inference YOLOv4 rknn model before?

**Comment by frootonator** [comment]
> I got a similar fault with conversion of yoloV8s: E RKNN: [01:25:20.303] failed to submit! op id: 1, op name: Conv:/model.0/conv/Conv, flags: 0x5, task start: 0, task number: 19, run task counter: 0, int status: 0

I've solved this problem adding Reshape layer. It reshapes (1, 255, 76, 76) dimension tensor to (1, 3, 85, 76, 76). I guess second dimension of input and output tensors relates to channel (which can be equal to 1, 3 and 4) by default. That's why the mistake was thrown. 

I met problems with input layers too but don't remember the issue. I'll try to suggest the solution later.

**Comment by frootonator** [comment]
> @frootonator did you solve it?

Yes, solved it by adding Reshape operator before output layer.

**Comment by gujiacheng** [comment]
> > @frootonator did you solve it?
> 
> Yes, solved it by adding Reshape operator before output layer.

how to do that , more specific？
