### ISSUE TITLE
Can you provide Python 3.8-3.10 package

### ISSUE THREAD

**Issue by Goose-Bomb** [rockchip-linux/rknn-toolkit2#9]
Python 3.6 is just too old, even the latest version of NumPy has dropped `<= 3.7` version support.

**Comment by rkchrome** [comment]
3.8 and higher python version is subject to more model test. If test success, new version will be release!

**Comment by rkchrome** [comment]
3.8 and higher python version is subject to more model test. If test success, new version will be release!

**Comment by henrykim1004** [comment]
Please provide library for Python 3.8

**Comment by Goose-Bomb** [comment]
Can you provide a python3.9 or 3.10 version package? Given that the python 3.8 package is available in the latest release, it should be simple to support higher python versions.
@rkchrome

**Comment by rickological** [comment]
What do you need from the community to release rknn_toolkit_lite2 for aarch64 for python 3.10 (Armbian)?

**Comment by henrykim1004** [comment]
Now we need for 3.10 version also.   Python is constantly being updated.   My new orange pi 5 comes with python 3.10 default.  It would be excellent if the python library is always up to the recent ones as well.

**Comment by ybz21** [comment]
we need for 3.10 version since ubuntu 22.04's python version is 3.10.
