### ISSUE TITLE
RKNN 二进制转文本

### ISSUE THREAD

**Issue by frootonator** [rockchip-linux/rknn-toolkit2#99]
你好，

有什么方法可以将 .rknn 二进制文件转换为 .txt 以查看它的结构。 我试图找到类似于 onnx-proto 的东西。 或者也许有一种方法可以解码 rknn 二进制文件？

如果有任何帮助，我将不胜感激。

**Comment by roman-tut-off** [comment]
Hello. 
Yoг can try using this site https://netron.app/
